<!DOCTYPE>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Tlumx application: an error occurred</title>  
  <meta charset="utf-8">
  <meta name="description" content="Tlumx Skeleton application">
  <style>
	body {font-family: Helvetica,Arial,sans-serif;font-size: 20px;line-height: 28px;padding:20px;}
	td { padding-right: 10px;}
	th { padding-right: 10px;}
	/*th { padding: 100px;}
	tr { margin: 10px;}*/
  </style>
</head>
<body>
  <h1>An error occurred</h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>  
  <h3>Message</h3>
  <p><?php echo $this->exception->getMessage() ?></p>                          
  <h3>Stack trace</h3>
  <table>
    <thead>
		<tr>
			<th>#</th>
			<th>File</th>
			<th>Line</th>
			<th>Class</th>
			<th>Function</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->exception->getTrace() as $k => $row): ?>
		<tr class="<?= ($k % 2 == 0) ? 'alt' : '' ?>">
			<td><?= $k ?></td>
			<td><?= isset($row['file']) ? $row['file'] : ''; ?></td>
			<td><?= isset($row['line']) ? $row['line'] : ''; ?></td>
			<td><?= isset($row['class']) ? $row['class'] : ''; ?></td>
			<td><?= isset($row['function']) ? $row['function'] : ''; ?></td>
		</tr>
	<?php endforeach; ?>
	</tbody>
  </table>
  <?php endif ?>
</body>
</html>
